WebApplication1/Models/ViewModels/AddCarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarRental.Models.ViewModels
{
    public class AddCarViewModel
    {
        public Car car;

        [Required(ErrorMessage = "Brand is required!")]
        public String brand;

        [Required(ErrorMessage = "Model is required!")]
        public String model;

        [Required(ErrorMessage = "Date is required!")]
        public DateTime date;

        [Required(ErrorMessage = "Photo is required!")]
        public String photoPath;

        [Required(ErrorMessage = "Price is required!")]
        public float price;
    }
}

WebApplication1/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.Models.AppDBContext;
using CarRental.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Controllers
{
    public class AddController : Controller
    {
        private readonly ApplicationDBContext _context;
        public AddController(ApplicationDBContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
          
            return View();
        }

        public async Task<IActionResult> ConfirmAdd(AddCarViewModel model)
        {
            Console.WriteLine("------+++----" + model.brand + " " + model.model + " " + model.price + " " + model.date);
            return View();
        }
    }
}

WebApplication1/Controllers/AdminCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.Models;
using CarRental.Models.AppDBContext;
using CarRental.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace CarRental.Controllers
{
    public class AdminCarController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly AddCarViewModel model;

        public AdminCarController(ApplicationDBContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var cars = await _context.Cars.ToListAsync();
            var carModel = new List<Car>();
            foreach (Car car in cars)
            {
                var aux = new Car();
                aux.brand = car.brand;
                aux.id = car.id;
                aux.model = car.model;
                aux.photoPath = car.photoPath;
                aux.fabricationDate = car.fabricationDate;
                aux.price = car.price;
                carModel.Add(aux);

            }
            ViewBag.cars = carModel;
            return View();
        }

        public async Task<IActionResult> AddCar(AddCarViewModel model)
        {
            Console.WriteLine("aici");
            return View();
        }

        public async Task<IActionResult> AddPage()
        {
            Console.WriteLine("Add page");
            return View();
        }

    }
}

WebApplication1/Views/AdminCar/AddCar.cshtml
@model CarRental.Models.ViewModels.AddCarViewModel
@{
    ViewData["Title"] = "Confirm add";
}
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css//bootstrap-morph.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/datepicker.css" />

</head>

<div>
    <h1>
        Add new car
    </h1>
</div>

<body>
    <form method="post">
        <div class="form-group">
            <label class=" form-label text-dark">Brand</label>
            <input asp-for="brand" class="form-control" />
            <span asp-validation-for="brand" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label class=" form-label text-dark">Model</label>
            <input asp-for="model" class="form-control" />
            <span asp-validation-for="model" class="text-danger"></span>
         </div>

        <div class="form-group">
            <label class=" form-label text-dark">Price</label>
            <input asp-for="price" class="form-control" />
            <span asp-validation-for="price" class="text-danger"></span>

         </div>

        <div>
            <label class=" form-label text-dark">Fabrication Date </label>
            <input asp-for="date" class="form-control datepicker-dropdown" name="fabricationDate" />
            <span asp-validation-for="date" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" asp-controller="Add" asp-action="ConfirmAdd">Rent Car</button>
    </form>
</body>

WebApplication1/Views/AdminCar/AddPage.cshtml
<!DOCTYPE html>
@model CarRental.Models.ViewModels.AddCarViewModel
@{
    ViewData["Title"] = "Add car page";
}
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css//bootstrap-morph.css" />
</head>
 <h1>
     Add new car
 </h1>
 <body>
     <div class="form-group">
         <a class="btn btn-primary" asp-area="" asp-controller="AdminCar" asp-action="AddCar">Add Car</a>
     </div>
 </body>

WebApplication1/Views/AdminCar/Index.cshtml
@model CarRental.Models.Car
@{
    ViewData["Title"] = "Cars";
}
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css//bootstrap-morph.css" />
</head>
<h1 style="text-size-adjust">Available cars</h1>
<table class="table table-striped ">
    <thead>
        <tr>
            <th style="color:black">Brand</th>
            <th style="color:black">Model</th>
            <th style="color:black">Fabrication Date</th>
            <th style="color:black">Price/Hour</th>
            <th style="color:black">Photo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in ViewBag.cars)
        {
            <tr>
                <td style="color:black">@car.brand</td>
                <td style="color:black">@car.model</td>
                <td style="color:AppWorkspace">@car.fabricationDate</td>
                <td style="color:darkred">@car.price</td>
                <td>
                    <img style="max-width:250px;max-height:150px" src="@car.photoPath" />
                </td>
            </tr>
        }
    </tbody>
</table>